### ISSUE TITLE
 "meta/ALL cell lines Scilife_CCK_CMB_2020-12-10. xlsx" is missing but required in "init. R"

### ISSUE THREAD

**Issue by malihhhh** [isabelle-leo/FORALL#9]
Dear author

Hello, I want to reproduce your code and learn. The first step is to run the "init. R" script. But the meta data is missing: "meta/ALL cell lines Scilife_CCK_CMB_2020-12-10. xlsx", in which "Commercial ALL cell lines" sheet is required. Sorry for taking up your time. If you don't mind, could you please add this file to the meta? Thank you very much!

**Comment by isabelle-leo** [comment]
Hello! Thanks for your interest in our work. The file you are looking for can be accessed from the paper: "Supplementary Data 1: Cell Line Panel and feature data". We generally chose not to upload data or tables on github if it would become available through other data hosting platforms or included in the publication, to avoid misleading versions or confusion in file names while the figure and table numbers might be changing. Let me know if you find something missing from the supplementary files and hope things go well in your code reproducing project.
